name = "spin-macho-casino-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-macho-casino.com.es"
HMAC_KEY = "1ab06096663dced8aef1543455f6f8c5aff5ce713efc901fbd02a2e2ac2ac44a"
COOKIE_NAME = "e55"
PLAY_PATH = "try-now"
BUTTON_ID = "p6a057760709cc006a23b0bc8e8b83e03"
GATE_SALT = "6506c6427385dda2"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "46wv"
CTA_SELECTOR = ".play-button"
